### PR TITLE
Added config option 'githooks.checklog.message-on-failure'.

### PR DESCRIPTION
**Pull request by mikkoi**
If there are any errors, then the contents of this option will be displayed after the other errors. It can contain e.g. instructions to the user on the commit restrictions.

### CODE REVIEW

**Comment by gnustavo** [comment]
This is a very good idea. So much so that I think it should be more general, allowing one to provide helpful messages for any plugin and a general one.

I've implemented this generalized idea in 6609feeeab90722fae614a2d564dcc3f6080c850. Can you tell me what do you think?

**Comment by gnustavo** [comment]
Ooops. Not so fast... I've just realized that my implementation is wrong. The specific githooks.plugin.help-on-error isn't working. I'll take a look at it.

**Comment by gnustavo** [comment]
OK. Now I think this works: c2bdb0cfa49226495cba3dfe0404e71b38b67193.

**Comment by mikkoi** [comment]
Hi,

Looks good. (I read the code, didn't run it).
You "globalized" the idea. :-)

Thanks.

## 

Mikko

On 2014-11-09 02:40, Gustavo Chaves wrote:

> OK. Now I think this works: c2bdb0c [1].
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].
> 
>   *
> 
> ## Links:
> 
> [1]
> https://github.com/gnustavo/Git-Hooks/commit/c2bdb0cfa49226495cba3dfe0404e71b38b67193
> [2] https://github.com/gnustavo/Git-Hooks/pull/6#issuecomment-62286982

## 

Mikko Koivunalho
LinkedIn: http://www.linkedin.com/in/MikkoKoivunalho
AboutMe: http://about.me/mikkokoivunalho
Blog: http://exercisesinintegrationanddelivery.blogspot.com

**Comment by gnustavo** [comment]
2014-11-10 9:11 GMT-02:00 Mikko Koivunalho notifications@github.com:

> Hi,
> 
> Looks good. (I read the code, didn't run it).
> You "globalized" the idea. :-)

Yes! Thanks.

I'll make a new release shortly. I just have to review another change
that's going to go together.

## 

Gustavo.

**Pull request closed without merging**
