### PR TITLE
Check commit author

### PR DESCRIPTION
**Pull request by mikkoi**
Hi, Gustavo,

I have created a new hook for Git::Hooks. It leans heavily on your work in CheckLog and uses your test routines, so I thought its place might be alongside CheckLog. CheckCommitAuthor checks that the author information included with commit "item" (but not commit message) is what is wanted. It uses three options for this: a) match against a regex, b) match against .mailmap file and c) match against the Git user. Due to Git's extremely relaxed attitude in this field, the most logical match would be against the .mailmap file. We have had problems with developers making commits with other than company email addresses. Would you include CheckCommitAuthor with Git::Hooks?

While I was programming it, I also fixed two minor bugs, they are in commits dec36ae and 1f07033. I also changed some tabs into spaces in file 't/test-functions.pl'.

t/test-functions.pl is very useful. I would like to join the earlier discussion and say that we should indeed "upgrade" it into a package.

### CODE REVIEW

**Comment by gnustavo** [comment]
Thank you, Mikko. The new plugin seems to be a worth addition to the distribution. I want to spend some time reviewing it in the next days.

I just rebased your whole branch to separate the changes in consolidated commits. I'll leave some questions to you in your commits.

**Comment by mikkoi** [comment]
CheckCommitAuthor is not yet 100% functional. The server-side is missing, and misses tests, too.

**Comment by mikkoi** [comment]
Server-side works. Also mailmap checking and matching against Git user work.

**Comment by gnustavo** [comment]
I'm sorry for taking so long to integrate this. I'm thinking about writing a more general plugin called CheckCommit which would integrate the current CheckLog with your CheckCommitAuthor, and could also implement more checks related to the meta-information of commits, such as the Commiter name and email, limit file sizes, commit notes, GPG signatures, etc. Please, bear with me.

**Comment by mikkoi** [comment]
No problem. Take your time.

**Comment by gnustavo** [comment]
Hi Mikko. I started from your ideas and code to come up with a plugin called Git::Hooks::CheckCommit that's a little more general. I've pushed it to it's own branch (checkcommit) to let you review it before integrating it on next. What do you think?

**Comment by mikkoi** [comment]
Hi, Gustavo,
I've gone through the code and documentation.
First of all, it's a good thing you added a check for signed commits. I've just read about some security breaches related to Git repositories. [A Git Horror Story: Repository Integrity With Signed Commits](http://mikegerwitz.com/papers/git-horror-story) We have to take these things into count (I mean the company).

I think we should not use post-commit hook for checking the identity. Fixing afterwards is annoying to users. Pre-commit or commit-msg would be better, I think.
Can you check the signature only after commit? Then maybe the checks should be separated. Checking the identity is not a security matter, since we can only check that the name and email address are valid (for our purpose). But we can't connect them with the actual user.
If we use the `check-mailmap` git command, we have to call it at every commit. But the Git::Mailmap object can be cached.
I like that you're using the package Email::Valid to check the email address is "sane".

**Comment by gnustavo** [comment]
2015-05-03 11:59 GMT-03:00 Mikko Koivunalho notifications@github.com:

> Hi, Gustavo,
> I've gone through the code and documentation.
> First of all, it's a good thing you added a check for signed commits. I've
> just read about some security breaches related to Git repositories. A Git
> Horror Story: Repository Integrity With Signed Commits
> http://mikegerwitz.com/papers/git-horror-story We have to take these
> things into count (I mean the company).
> 
> Yeah, this very paper is in my "to-read" list for a while. :-)
> 
> I think we should not use post-commit hook for checking the identity.
> Fixing afterwards is annoying to users. Pre-commit or commit-msg would be
> better, I think.
> 
> Hmm... during the pre-commit I don't have the complete commit and I can't
> perform all the checks. The signature check, for example. The identity
> checks I could perform based on the environment variables that you used in
> your code. I even started from that but decided to make all checks on the
> post-commit afterwards because it made the coding simpler.

Personally, I don't like to have the pre-commit hooks abort the commits on
me because this forces me to fix things and then retry the commit and then
I'll have to reword the commit message or fetch it from the .git/COMMIT_MSG
file, which by this time may have been ovewritten by another commit. That's
why I set the githooks.abort-commit to 0 on my personal ~/.gitconfig. I
find it simpler to fix whatever needs fixing and the simply invoke "git
commit --amend" because the commit message is saved for me.

Moreover, I don't think the identity checks are all that relevant during
the commit, because normally the user configures it once and have it right
forever. I think they're more relevant to the server hooks (update and
pre-receive), which must reject commits from different users.

> If we use the check-mailmap git command, we have to call it at every
> commit. But the Git::Mailmap object can be cached.
> 
> Good point. I'll cache this information too.
> 
> I like that you're using the package Email::Valid to check the email
> address is "sane".
> 
> Yeah, that was almost an afterthought but I think it's very useful too.

## 

Gustavo.

**Comment by mikkoi** [comment]
> [...] then retry the commit and then I'll have to reword the commit message or fetch it from the .git/COMMIT_MSG file, which by this time may have been ovewritten by another commit.

We have a different workflow. :-) My commit messages are normally short. In fact, they are often just the Jira ticket number and its subject.

I would still go for the pre-commit hook, because checking the user's name and email are in my mind less about checking a commit's content and more about checking that the user has configured his Git environment properly. Because, as you said, it is normally done only once, when setting up a new programming environment.

**Comment by gnustavo** [comment]
2015-05-04 3:09 GMT-03:00 Mikko Koivunalho notifications@github.com:

> [...] then retry the commit and then I'll have to reword the commit
> message or fetch it from the .git/COMMIT_MSG file, which by this time may
> have been ovewritten by another commit.
> 
> We have a different workflow. :-) My commit messages are normally short.
> In fact, they are often just the Jira ticket number and its subject.
> 
> Hmmm... I have a few suggestions to you
> https://metacpan.org/pod/Git::Hooks::CheckLog#REFERENCES. :-)
> 
> I would still go for the pre-commit hook, because checking the user's name
> and email are in my mind less about checking a commit's content and more
> about checking that the user has configured his Git environment properly.
> Because, as you said, it is normally done only once, when setting up a new
> programming environment.
> 
> OK. I changed CheckCommit so that it does the identity checks in the
> pre-commit hook, leaving only the signature checks in the post-commit hook.
> Since the user can configure the githooks.abort-commit option he can choose
> if he want to have the commit abort or not.

I pushed the result to next
https://github.com/gnustavo/Git-Hooks/blob/next/lib/Git/Hooks/CheckCommit.pm.
What do you think?

## 

Gustavo.

**Comment by gnustavo** [comment]
I shouldn't have pushed it to next yet. I've just rebased it to its own branch [checkcommit](https://github.com/gnustavo/Git-Hooks/commit/0f40f4fb02b208f76ac01e33fab05cc41cca4e5d).

**Comment by mikkoi** [comment]
What was the problem?
Seems ok to me. (Didn't run, though.)

**Comment by gnustavo** [comment]
I just uploaded v1.8.0 to PAUSE including the new Git::Hooks::CheckCommit hook which implements this. Thanks!

**Pull request closed without merging**
