### PR TITLE
Avoided triggering 'Invalid range' error by calling get_affected_ref_commit_ids on newly created branch (ref)

### PR DESCRIPTION
**Pull request by mpolishchuck**

### CODE REVIEW

**Comment by mpolishchuck** [comment]
Hmm... get_commits() method returns ARRAY of HASH refs with commit parameters... in this case better to change line 347 to

```
$affected->{$ref}{ids} = [map { $_->{'commit'} } $git->get_commits(@range)];
```

because we need to get commits sha identifiers instead of full parameters.

But if we writing hook with invocation of two methods: get_affected_ref_commit_ids and get_affected_ref_commits, we have double job in get_commits method. So I think better fix is (line 347):

```
$affected->{$ref}{ids} = [map { $_->{'commit'} } $git->get_affected_ref_commits($ref)];
```

This will cache results of get_affected_ref_commits and excessive call of git binary will be avoided.

**Comment by gnustavo** [comment]
You're completely right. I've squashed your two commits and pushed it as 628c7a4. I'll cut a new release soon.

BTW, I've just noticed that the routine get_affected_ref_commit_ids isn't used anywhere in the Git::Hooks distribution. How did you noticed the problem? Are you implementing another plugin? I'm just curious.

Thank you!

**Comment by mpolishchuck** [comment]
I implementing server hook for deploying my project into production server. At the start I just tried to get list of commit sha to understand how Git::Hooks works. I got error immediately after pushing into empty (testing) repository.

**Comment by gnustavo** [comment]
2015-01-06 9:28 GMT-02:00 Maxim Polishchuck notifications@github.com:

> I implementing server hook for deploying my project into production
> server. At the start I just tried to get list of commit sha to understand
> how Git::Hooks works. I got error immediately after pushing into empty
> (testing) repository.

Cool.

My test suite really needs to grow. :-)

## 

Gustavo.

**Comment by gnustavo** [comment]
Maxim, I've just released Git::Hooks 1.6.1 containing your fix. It should
appear on CPAN shortly.

2015-01-06 10:43 GMT-02:00 Gustavo Chaves gustavo@gnustavo.com:

> 2015-01-06 9:28 GMT-02:00 Maxim Polishchuck notifications@github.com:
> 
> > I implementing server hook for deploying my project into production
> > server. At the start I just tried to get list of commit sha to understand
> > how Git::Hooks works. I got error immediately after pushing into empty
> > (testing) repository.
> 
> Cool.
> 
> My test suite really needs to grow. :-)
> 
> ## 
> 
> Gustavo.

## 

Gustavo.

**Comment by mpolishchuck** [comment]
Gustavo, thank you very much :-)

**Pull request closed without merging**
