### PR TITLE
 Update jira

### PR DESCRIPTION
**Pull request by mikkoi**
Hi,
Remember when before Christmas I suggested the CheckJira could also be used to write to Jira. Well, instead of using CheckJira plugin, I wrote this: UpdateJira. I only operates on post-commit and post-receive hooks. Uses mostly the same parameters as CheckJira, so I thought maybe it belongs in the same distro with it.

### CODE REVIEW

**Comment by gnustavo** [comment]
This is really nice, but I think it would be better to integrate the new functionality in CheckJira in order to avoid code and configuration duplication. Is it ok to you if I do that?

Also, tell me, why the action-\* configuration must match a regexp? I don't quite see the use case for that.

**Comment by mikkoi** [comment]
Hi,
You can merge UpdateJira to CheckJira. That was my first idea. But I decided to make it separate because I think they do two different things. Updating is more dangerous and requires more user privileges.
It is also a question of naming. I imagine a series of hooks with Update-something, like UpdateReviewBoard, UpdateRedmine, UpdateTwitter. (Talking about naming, I'm also thinking about Trigger-somethings, like TriggerMQ, TriggerHTTP/Webhook, TriggerEmail, TriggerJenkins/CIServer for things which don't need to be completed right away, and don't need all the repo information.

action-\* currently only has one command: Add a new comment. Others are in the plans: close ticket, change status to wait customer input / wait code review. Different commit messages would create different action: "Bugfix JIRA#PROJ-123" -> close without wait, "Partial JIRA#PROJ-123" -> Wait customer input, "Finished..." -> Wait code review. And so on.

**Comment by gnustavo** [comment]
I integrated the notification functionality on CheckJira. It's optional and enabled by the githooks.checkjira.comment option.

I think other ticketing systems should have their own CheckSomething plugin offering funcionatity equivalent of CheckJira.

**Comment by gnustavo** [comment]
I just uploaded v1.8.0 to PAUSE including this new functionality. Thanks!

**Pull request closed without merging**
