### PR TITLE
Change Temp File Naming

### PR DESCRIPTION
**Pull request by mikkoi**
Some file checkers, e.g. PerlCritic and Python Lint complain of invalid filenames. We should preserve the file name and path when initiating the Git::Hooks::CheckFile arguments.

Instead of copying the changed files to file like '/tmp/qwertyuipo', we create a dir like '/tmp/qwertyuipo' and copy the changed file there, e.g. '/tmp/qwertyuipo/dir/path/filename.txt'.

### CODE REVIEW

**Comment by gnustavo** [comment]
I've made some inline comments on #7.

**Comment by mikkoi** [comment]
Fixed the issues you mentioned.
I also added some code to check if the $ref is actually used (contains a SHA), or not.

**Comment by mikkoi** [comment]
Works.

**Comment by gnustavo** [comment]
I've cherry-picked  7321627 on next but I've some doubts about  9d3a5c0 described in the preceding comments.

I'm closing this pull request because it's too dirty already. Please, if you want to make any other changes start a new pull request from the current next branch, ok? Otherwise, let me know so that I can cut a new release.

**Pull request closed without merging**
